//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Ajedrez_v_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ajedrez_v1Entities1 : DbContext
    {
        public Ajedrez_v1Entities1()
            : base("name=Ajedrez_v1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<articulo_estado> articulo_estado { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<comentario_estado> comentario_estado { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
