//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Ajedrez_v_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listaventa
    {
        public int idlistaventa { get; set; }
        public int idventa { get; set; }
        public int idproducto { get; set; }
        public int Cantidad { get; set; }
        public double total { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
